// import { Inter } from "next/font/google";
import Footer from "./components/footer/footer";
import Header from "./components/header/header";
import "./globals.css";
import { Poppins } from "next/font/google";


// const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body suppressHydrationWarning={true} className={poppins.className}>
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    );
}
